### PR TITLE
Add support for allowlists/denylists, bump to 1.6

### LINKED ISSUE #13: Add ability to allowlist features to be mixed in Cargo.toml
My crate has a lot of features and the exponential growth is becoming a problem. I don't actually care about the full matrix, I'd like a subset of them to be cargo-all-features-tested. Would it be possible to get a metadata key for this?

### PR DESCRIPTION
**Pull request by Manishearth**
Fixes #13

It occurs to me that there's utility for an `always_include` key as well, that always includes a feature in the list after allow/deny have been applied. Thoughts @frewsxcv?

### CODE REVIEW

**Review by frewsxcv — APPROVED** [review]
Looks good to me, thanks @Manishearth! Do you have capacity to update the README with these new configuration options?

**Comment by Manishearth** [comment]
Will do!

**Comment by Manishearth** [comment]
Done!

**Review by frewsxcv — APPROVED** [review]
Thanks @Manishearth! Will cut a release now

**Pull request merged**
